---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sfmodaca/dev.hoboscompanion.org
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp index.js $DEPLOYPATH
    - /bin/cp auth.js $DEPLOYPATH
    - /bin/cp db.js $DEPLOYPATH
    - /bin/cp view.js $DEPLOYPATH
    - /bin/cp middleware.js $DEPLOYPATH
    - /bin/cp utils.js $DEPLOYPATH
    - /bin/cp -r models $DEPLOYPATH
    - /bin/cp -r public $DEPLOYPATH
    - /bin/cp -r routes $DEPLOYPATH
    - /bin/cp -r views $DEPLOYPATH